language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
